### ISSUE TITLE
Add datetime

### ISSUE THREAD

**Issue by Rizhiy** [joaopalmeiro/flake8-import-conventions#25]
Add `import datetime as dt`?

**Comment by joaopalmeiro** [comment]
Hi, @Rizhiy!

Thanks for your suggestion and I apologize for the HUGE delay in responding! 

As the suggestion does not seem like something standardized (for example, there is no reference to it in the [documentation](https://docs.python.org/3/library/datetime.html)), I will not include it in the plugin.
